version: '3.5'

services:

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=debugerserver
    depends_on:
      - db
    container_name: cont_php

  web:
    image: nginx:stable
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - php
    container_name: cont_web

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
        - "8101:3306"
    environment:
      MYSQL_DATABASE: framework_db
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: cont_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - "8080:80"
    environment:
        - PMA_ARBITRARY=1
    depends_on:
        - db
    container_name: cont_phpmyadmin

  node:
    container_name: cont_node
    build:
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./:/app

