#FROM node:alpine
#
#RUN apt-get update && apt-get install -y \
#    vim \
#    zip \
#    unzip \
#    curl &&\
#    npm install
#
#COPY ./ /var/www
#WORKDIR /var/www
#
#ENTRYPOINT ["npm"]
#
#EXPOSE 8080